name: Deploy Python docs

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  build:
    name: Deploy Python docs
    runs-on: ubuntu-latest
    env:
      CI: "TRUE"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Deploy docs
        env:
          GIT_COMMITTER_NAME: CI
          GIT_COMMITTER_EMAIL: ci-bot@example.com
        run: |
          VERSION=$(git describe --tags --match="v*" --abbrev=0)
          echo $VERSION

          if echo $VERSION | cut -c 2- | grep -q "[A-Za-z]"; then
            echo "Is beta version"
            uv run --group docs mike deploy $VERSION --update-aliases --push
          else
            echo "Is NOT beta version"
            uv run --group docs mike deploy $VERSION latest --update-aliases --push
          fi
